version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certificados/cert.pem:/etc/nginx/certs/cert.pem:ro
      - ./nginx/certificados/key.pem:/etc/nginx/certs/key.pem:ro
